# Generated by Django 3.2.6 on 2021-09-08 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Custaddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_complete_address', models.CharField(max_length=255)),
                ('user_floor', models.CharField(max_length=255)),
                ('user_how_to_reach', models.CharField(max_length=255)),
                ('user_address_type', models.CharField(max_length=255)),
                ('phone_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
