# Generated by Django 3.2.6 on 2021-09-12 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner_with_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Restaurant_Name', models.CharField(max_length=255, null=True)),
                ('Mobile_Number', models.IntegerField()),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('City', models.CharField(max_length=15, null=True)),
                ('fssai_num', models.CharField(max_length=255, null=True)),
                ('fssai_exp_date', models.DateField(null=True)),
                ('own_name', models.CharField(max_length=50, null=True)),
                ('own_aadhar', models.IntegerField(null=True)),
                ('aadhar_file', models.FileField(null=True, upload_to='media/', verbose_name='')),
                ('own_address', models.CharField(max_length=250, null=True)),
                ('own_mobile', models.IntegerField(null=True)),
                ('gst_num', models.CharField(max_length=255, null=True)),
                ('gst_file', models.FileField(null=True, upload_to='media/', verbose_name='')),
                ('pan_num', models.CharField(max_length=255, null=True)),
                ('acc_num', models.IntegerField(null=True)),
                ('bank_name', models.CharField(max_length=50, null=True)),
                ('branch_name', models.CharField(max_length=100, null=True)),
                ('ifsc_code', models.CharField(max_length=100, null=True)),
                ('pan_file', models.FileField(null=True, upload_to='media/', verbose_name='')),
                ('sign_file', models.FileField(null=True, upload_to='media/', verbose_name='')),
                ('img_file', models.FileField(null=True, upload_to='media/', verbose_name='')),
                ('menu_file', models.FileField(null=True, upload_to='media/', verbose_name='')),
            ],
        ),
    ]
