# Generated by Django 3.2.6 on 2021-09-10 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partnerwithus', '0006_alter_partner_with_us_aadhar_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner_with_us',
            name='gst_file',
            field=models.FileField(null=True, upload_to='media/', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='partner_with_us',
            name='img_file',
            field=models.FileField(null=True, upload_to='media/', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='partner_with_us',
            name='menu_file',
            field=models.FileField(null=True, upload_to='media/', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='partner_with_us',
            name='sign_file',
            field=models.FileField(null=True, upload_to='media/', verbose_name=''),
        ),
    ]
