# Generated by Django 3.2.6 on 2021-09-10 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partnerwithus', '0007_auto_20210910_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner_with_us',
            name='pan_file',
            field=models.FileField(null=True, upload_to='media/', verbose_name=''),
        ),
    ]
