# Generated by Django 3.2.6 on 2021-09-12 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partnerwithus', '0008_partner_with_us_pan_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner_with_us',
            name='fssai_num',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='partner_with_us',
            name='gst_num',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='partner_with_us',
            name='pan_num',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
