# Generated by Django 3.2.6 on 2021-09-12 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('contact', models.IntegerField(max_length=12)),
                ('alternate_contact', models.IntegerField(max_length=12)),
                ('gender', models.CharField(max_length=10)),
                ('birthdate', models.DateField(null=True)),
                ('address', models.TextField(max_length=255)),
                ('state', models.CharField(max_length=25)),
                ('city', models.CharField(max_length=25)),
                ('nationality', models.CharField(max_length=25)),
                ('pincode', models.IntegerField(max_length=6)),
                ('driving_license', models.CharField(max_length=255)),
                ('vehicle', models.CharField(max_length=10)),
                ('identity', models.CharField(max_length=10)),
                ('privacy_policy', models.BooleanField()),
            ],
        ),
    ]
