# Generated by Django 3.2.6 on 2021-09-12 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='driving_license',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='privacy_policy',
            field=models.BooleanField(null=True),
        ),
    ]
